import {
  ACCESS_TOKEN,
  LOCALHOST,
  MAIN_MENU_ITEMS,
  PRODUCTS_SERVICE_PATH,
  AUTH_SERVICE_PATH,
} from "./utils";
export {
  LOCALHOST,
  ACCESS_TOKEN,
  MAIN_MENU_ITEMS,
  PRODUCTS_SERVICE_PATH,
  AUTH_SERVICE_PATH,
};
